# dynamic octree
dyna_octree:
  resolution: [0.8, 0.8, 0.8]
  # resolution: [5, 5, 5] 
  depth: 5

plane_seg:
  ransac_iter: 5
  ransac_thd: 0.2 # meter. 
  merge_thd_p: 0.3 # meter
  merge_thd_n: 3 # degree
  eigen_thd: 10

benchmarks:
  root: "./data/LiBIM-UST-raw"
  seq: "2f_office_02"
  interval: "30m"
  maptype: "submap3d"
  min_height: -2.4
