# dynamic octree
dyna_octree:
  resolution: [0.8, 0.8, 0.8]
  # resolution: [5, 5, 5] 
  depth: 5

plane_seg:
  ransac_iter: 5
  ransac_thd: 0.02 # meter.
  merge_thd_p: 0.2 # meter
  merge_thd_n: 2 # degree
  eigen_thd: 10

benchmarks:
  root: "./data/LiBIM-UST-raw"
  seq: "3f_office_03"
  maptype: "frame"
  min_height: -1.5
